name: stk
channels:
  - defaults
dependencies:
  - pip
  - pip:
    - gym
    - nltk
    - pandas
    - pandas_gbq
    - plotly
    - pytest
    - ray
    - requests
    - scikit_learn
    - simplepipeline
    - stable_baselines3
    - streamlit
    - tqdm
    - wandb
    - yfinance
    - h5py
    - orjson
    - tensorboard
variables:
  WANDB_DIR: F:/wandb/
